# Generated by Django 4.1 on 2022-08-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('phone', models.IntegerField()),
                ('slug', models.SlugField()),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.school', verbose_name='sid')),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('standardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.standard', verbose_name='sid')),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sid', models.CharField(max_length=100)),
                ('qr', models.CharField(max_length=100)),
                ('parentNo', models.IntegerField()),
                ('slug', models.SlugField()),
                ('standardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendence.standard', verbose_name='sid')),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
        migrations.AddField(
            model_name='standard',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.teacher', verbose_name='sid'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField(null=True)),
                ('remark', models.CharField(blank=True, max_length=5000, null=True)),
                ('slug', models.SlugField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.standard', verbose_name='sid')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student', verbose_name='sid')),
            ],
            options={
                'ordering': ('classId',),
            },
        ),
    ]
